name: Pull updates from hunyanjie/You-Get-Gui
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  pull_update_txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Pull update.txt
      env:
        SOURCE_REPO: "hunyanjie/You-Get-Gui"
        SOURCE_BRANCH: "main"
        SOURCE_FILE: "update.txt"
        DESTINATION_BRANCH: "main"
      run: |
        git clone https://github.com/$SOURCE_REPO.git
        cd You-Get-Gui
        git checkout $SOURCE_BRANCH
        cp $SOURCE_FILE ../hunyanjie.github.io/file/project/You-Get-GUI/
        cd ../hunyanjie.github.io
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add file/project/You-Get-GUI/update.txt
        git commit -m "Pull update.txt from You-Get-Gui"
        git push origin $DESTINATION_BRANCH
